# **Camera Simulator Usage**

this is a tutorial that shows how to use the camera_simulator module. 
Before starting please install the required libraries, you can install them using

*pip install -r requirements.txt*


Now you have to import the Lens and Sensor Classes that belongs to camera_simulator module. you can do it as follows:


In [38]:
import numpy as np # We will use numpy for creating 2D arrays as examples
from camera_simulator import Lens,Sensor # Importing the classes

#### Now lets use the Lens class:


for using the class you have to intanciate the class and we are going to create an object called lens:
As you can see we are initializing the class with two variables which are called width and height
those variables are the width and height of the camera lens.

In [12]:
height= 2
width = 3
lens = Lens(height,width)
print("the size of the image obtained with the lens is : ",(lens.height,lens.width))

the size of the image obtained with the lens is :  (2, 3)


you could also instanciate the class with no variables: but if you want to use it you will have to define the properties of the object after the instance was created

In [13]:
lens = Lens()
lens.height = 2
lens.width = 3
print("the size of the image obtained with the lens is : ",(lens.height,lens.width))

the size of the image obtained with the lens is :  (2, 3)


It is very important that you initialize the instance with integers, otherwise you will get an exception Error:


In [14]:
height= 2
width = "3"
lens = Lens(height,width)

TypeError: width and height must be integer values

In [16]:
lens = Lens()
lens.height = 2
lens.width = True

TypeError: width must be an integer value

After you have created the lens instance correctly you can proceed to use the process function. this function Validates that the shape of the input numpy data matches the Lens height and width properties.

Lets say that you have a 2D numpy Array called example_array and you want to know if that array matches the lens height and width properties:

In [19]:
example_array = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
print(example_array)

[[1 2 3]
 [4 5 6]]


now you will process that array just like the following cell code.



In [20]:
height= 2
width = 3
lens = Lens(height,width)
print(lens.process(example_array))

[[1 2 3]
 [4 5 6]]


Note that if the lens and the image sizes match then the function lens.process(example_array) will return the same array (example_array). otherwise it will return a ValueError:

In [21]:
lens.height = 3
lens.width = 4
print(lens.process(example_array))

ValueError: Shape of the image does not match the Lens

You could also enable/dissable the process function in the object using the enable property:

In [23]:
lens.height = 2
lens.width = 3
print(lens.process(example_array))
lens.enable = False
print(lens.process(example_array))

[[1 2 3]
 [4 5 6]]


ValueError: Process is not enabled

Using the Sensor Class is very similar to the Lens class, but now this class will emulate how to apply the gain of a sensor to an input 2D array.

So the sensor could be initialized with an integer or you coould just set the gain value like this:

Note that the default gain of any sensor is 1


In [26]:
gain = 3
sensor = Sensor(gain)
print("the gain of the sensor is : ",(sensor.gain))
sensor2 = Sensor()
sensor2.gain = 4
print("the gain of the sensor 2  is : ",(sensor2.gain))
sensor3 = Sensor()
print("the gain of the sensor 3  is : ",(sensor3.gain))

the gain of the sensor is :  3
the gain of the sensor 2  is :  4
the gain of the sensor 3  is :  1


Again you have to be careful choosing the gain as an integer, otherwise you will get an error.

In [27]:
sensor3 = Sensor()
sensor2.gain = "10"
print("the gain of the sensor 3  is : ",(sensor3.gain))

TypeError: Gain must be an integer value

Now if you have set correctly the gain of the sensor you could proceed to apply the process method wich will apply that gain to a certain 2D array 
Note that  

In [35]:
example_array = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
print("Initial Array: \n ", example_array)

sensor.gain = 3
print("Sensor after applying the gain:\n ",sensor.process(example_array))

Initial Array: 
  [[1 2 3]
 [4 5 6]]
Sensor after applying the gain:
  [[ 3  6  9]
 [12 15 18]]


As you can see the gain is a multiplication to the original image, so in this case if the gain was 3. then each pixel or each element will be multiplied by 3

Just like the Lens Class we could also dissable the process method using the enable property:

In [36]:
example_array = np.array([[1, 2, 3], [4, 5, 6]], np.int32)
sensor.gain = 3
print("Sensor after applying the gain:\n ",sensor.process(example_array))
sensor.enable = False
print("Sensor after applying the gain:\n ",sensor.process(example_array))

Sensor after applying the gain:
  [[ 3  6  9]
 [12 15 18]]


ValueError: Process is not enabled

## Congratulations, right now you are be able to use the camera_simulator module correctly.